/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as CrazyOrbitRouteImport } from './routes/crazy-orbit'
import { Route as BotAudioRouteImport } from './routes/bot-audio'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CrazyOrbitRoute = CrazyOrbitRouteImport.update({
  id: '/crazy-orbit',
  path: '/crazy-orbit',
  getParentRoute: () => rootRouteImport,
} as any)
const BotAudioRoute = BotAudioRouteImport.update({
  id: '/bot-audio',
  path: '/bot-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bot-audio': typeof BotAudioRoute
  '/crazy-orbit': typeof CrazyOrbitRoute
  '/portfolio': typeof PortfolioRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bot-audio': typeof BotAudioRoute
  '/crazy-orbit': typeof CrazyOrbitRoute
  '/portfolio': typeof PortfolioRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bot-audio': typeof BotAudioRoute
  '/crazy-orbit': typeof CrazyOrbitRoute
  '/portfolio': typeof PortfolioRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bot-audio'
    | '/crazy-orbit'
    | '/portfolio'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/bot-audio' | '/crazy-orbit' | '/portfolio' | '/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bot-audio'
    | '/crazy-orbit'
    | '/portfolio'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BotAudioRoute: typeof BotAudioRoute
  CrazyOrbitRoute: typeof CrazyOrbitRoute
  PortfolioRoute: typeof PortfolioRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crazy-orbit': {
      id: '/crazy-orbit'
      path: '/crazy-orbit'
      fullPath: '/crazy-orbit'
      preLoaderRoute: typeof CrazyOrbitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot-audio': {
      id: '/bot-audio'
      path: '/bot-audio'
      fullPath: '/bot-audio'
      preLoaderRoute: typeof BotAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BotAudioRoute: BotAudioRoute,
  CrazyOrbitRoute: CrazyOrbitRoute,
  PortfolioRoute: PortfolioRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
